55303 NewFilesPublished Events Are Being Rejected
UKHO/Maritime-Safety-Information pull request #106
Opened 2022-08-25 08:34 UTC by Avinash15515

2022-08-25 11:43 UTC, usha13529 approved these changes
Thanks @Avinash15515. Looks good to me.

2022-08-25 15:02 UTC, Chownder requested changes
Is it possible to provide some kind of automated testing around this, given that these changes are from a bug found in Live?

2022-08-26 09:50 UTC, usha13529 approved these changes

2022-08-30 14:48 UTC, ajasonca approved these changes
Looks good, thanks.

2022-08-30 14:54 UTC, merged