Implement logging configuration
UKHO/Maritime-Safety-Information pull request #5
Opened 2022-04-21 11:31 UTC by ganpat-tech

PR contains code for logging configuration  :-
UKHO EventHub logger
Azure AppInsights logger
File based logger (only for local development)

2022-04-21 15:26 UTC, usha13529 requested changes
Minor comments to address please.

2022-04-21 15:26 UTC, usha13529 commented on NVDSuppressions.xml
> +    This is a false positive. These two CVEs references a C library softmagic.c which is not used by ESS
```suggestion
    This is a false positive. These two CVEs references a C library softmagic.c which is not used by MSI
```

2022-04-21 15:26 UTC, usha13529 commented on NVDSuppressions.xml
> +    This is a false positive in cdf.c which is not used by ESS
```suggestion
    This is a false positive in cdf.c which is not used by MSI
```

2022-04-21 16:35 UTC, ganpat-tech commented on NVDSuppressions.xml
> +    This is a false positive. These two CVEs references a C library softmagic.c which is not used by ESS
Thanks for highlighting, done change.

2022-04-21 16:36 UTC, ganpat-tech commented on NVDSuppressions.xml
> +    This is a false positive in cdf.c which is not used by ESS
done change.

2022-04-21 17:10 UTC, barrie-cooper commented on NVDSuppressions.xml
> +   ]]></notes>
```suggestion
   This is a false positive as the vulnerability exists in a NPM Javascript package named 'Async' and not the nuget .NET package named 'Serilog.Sinks.Async'.
   ]]></notes>
```

2022-04-22 05:30 UTC, ganpat-tech commented on NVDSuppressions.xml
> +   ]]></notes>
Thanks for highlighting, done change.

2022-04-22 05:40 UTC, usha13529 approved these changes
Thanks for the changes @ganpat-tech. LGTM.

2022-04-22 07:08 UTC, barrie-cooper approved these changes
LGTM, thanks @ganpat-tech

2022-04-22 07:08 UTC, merged