WIP - Feature/48109 analytics and cookie management
UKHO/Maritime-Safety-Information pull request #56
Opened 2022-06-23 14:00 UTC by Ashish15251

Automation test cases remaining.

2022-06-29 13:02 UTC, usha13529 requested changes
Please fix the failing unit test cases.

2022-06-30 05:09 UTC, Ashish15251 commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/appsettings.Development.json
> +    "GTMID": ""
Changes Done

2022-06-30 05:09 UTC, Ashish15251 commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Common/Extensions/DateTimeExtensions.cs
>          }
Changes Done

2022-06-30 05:40 UTC, Ashish15251 commented
Automation test cases not required.

2022-06-30 07:20 UTC, barrie-cooper commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/appsettings.json
> +    "GTMID": ""
Could we have this as `GoogleTagManagerID` please:
```suggestion
    "GoogleTagManagerID": ""
```

2022-06-30 10:23 UTC, usha13529 approved these changes
Thanks @Ashish15251. Looks good to me.

2022-07-01 10:31 UTC, Ashish15251 commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/Views/Home/Index.cshtml
> +    (function (w, d, s, l, i) {
Done

2022-07-01 14:44 UTC, merged