45750-About NMs Tab
UKHO/Maritime-Safety-Information pull request #68
Opened 2022-07-08 05:41 UTC by Shirin14926

Code changes, Unit test and UI changes for About tab
Also, added comment about the location of the instructions for NM Integration Tests

2022-07-08 11:10 UTC, usha13529 requested changes
Few review comments to fix please.

2022-07-08 11:10 UTC, usha13529 commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/Views/NoticestoMariners/About.cshtml
> +    ViewData["Header"] = "Notice to Mariners";
```suggestion
    ViewData["Header"] = "Notices to Mariners";
```

2022-07-08 12:45 UTC, Shirin14926 commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/Views/NoticestoMariners/About.cshtml
> +    ViewData["Header"] = "Notice to Mariners";
Done as expected

2022-07-08 12:48 UTC, Shirin14926 commented on Tests/AutoTests/AccessibilityTest/accessebility-noticetomarineabout.spec.ts
> +test.describe("MSI Notice to Marine Page Accessibility Test", () => {
Done as expected

2022-07-08 12:49 UTC, Shirin14926 commented on Tests/AutoTests/AccessibilityTest/accessebility-noticetomarineabout.spec.ts
> +    test('Notice to Marine About page should be accessible', async ({ page }) => {
Have corrected the filename

2022-07-11 07:42 UTC, usha13529 approved these changes
Thanks for the changes @Shirin14926. Looks good to me.

2022-07-11 11:31 UTC, barrie-cooper reviewed
Just a few minor points

2022-07-11 11:31 UTC, barrie-cooper commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/Views/NoticestoMariners/About.cshtml
> +</p>-->
Please remove commented out link:
```suggestion
```

2022-07-11 12:16 UTC, Shirin14926 commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/Views/NoticestoMariners/About.cshtml
> +    New Notice to Mariners tracings
Done, Thanks

2022-07-11 12:16 UTC, Shirin14926 commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/Views/NoticestoMariners/About.cshtml
> +    Please see our publication <a href="https://www.admiralty.co.uk/publications/publications-and-reference-guides/general-publications-and-reference-guides" aria-label="How to keep your ADMIRALTY Pr
Removed, Thanks

2022-07-11 12:16 UTC, Shirin14926 commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/Views/NoticestoMariners/About.cshtml
> +    <a href="~/nms/about/ADMIRALTY-NMs-Guidance-Notes-Sept2015.pdf" target="_blank" aria-label="View the guidance notes for Notice to Mariners here PDF opens in new tab">View the guidance notes for N
Done, Thanks

2022-07-11 12:17 UTC, Shirin14926 commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/Views/NoticestoMariners/About.cshtml
> +    The ADMIRALTY Notices to Mariners Online service enables mariners to download NMs directly from this website. NMs Online can be accessed on this website under ‘Notice for Mariners documents’.
Done, Thanks

2022-07-11 12:17 UTC, Shirin14926 commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/Views/NoticestoMariners/About.cshtml
> +</p>-->
Removed,Thanks

2022-07-11 12:55 UTC, barrie-cooper approved these changes
LGTM, thanks @Shirin14926

2022-07-11 12:55 UTC, merged