WIP Feature/45762 vars tab
UKHO/Maritime-Safety-Information pull request #76
Opened 2022-07-21 06:40 UTC by mubeenMastek

2022-07-21 12:12 UTC, usha13529 requested changes
One minor comment to address please.

2022-07-21 12:12 UTC, usha13529 commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/Views/NoticestoMariners/Resellers.cshtml
> +    ViewData["Header"] = "Notice to Mariners";
```suggestion
    ViewData["Header"] = "Notices to Mariners";
```

2022-07-21 13:57 UTC, mubeenMastek commented on UKHO.MaritimeSafetyInformation.Web/UKHO.MaritimeSafetyInformation.Web/Views/NoticestoMariners/Resellers.cshtml
> +    ViewData["Header"] = "Notice to Mariners";
Changes done.

2022-07-27 13:18 UTC, Chownder approved these changes

2022-07-27 15:27 UTC, barrie-cooper approved these changes
LGTM, thanks @mubeenMastek 

Will merge once live release is complete tomorrow.

2022-07-28 11:25 UTC, merged